#!/usr/bin/env python
import os
import grizzled.os

from resweb import server
from itty import run_itty

def main():
    from optparse import OptionParser
    usage = "usage: %prog [options]"
    parser = OptionParser(usage)
    parser.add_option("-d", "--daemon", 
                    dest="daemon", 
                    action="store_false",
                    help="enable daemon mode")
    parser.add_option("--host",
                    dest="host",
                    default="localhost",
                    metavar="HOST")
    parser.add_option("--port",
                    dest="port",
                    type="int", 
                    default=8080)
    parser.add_option("--dsn",dest="dsn",help="redis server to display")
    (options,args) = parser.parse_args()
    if options.dsn:
        from pyres import ResQ
        server.HOST = ResQ(options.dsn)
    
    if options.daemon is not None:
        grizzled.os.WORKDIR = os.path.abspath(os.path.dirname(__file__))
        grizzled.os.daemonize()
        
    run_itty(host=options.host, port=options.port)

if __name__ == "__main__":
    main()